# Generated by Django 4.2 on 2023-04-10 02:19

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_students_daily_allowance_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='daily_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.DecimalValidator(5, 2)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 2, 19, 3, 7616, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_schooling',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
    ]
