# Generated by Django 4.2 on 2023-04-10 03:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_students_last_time_at_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 3, 3, 44, 997436, tzinfo=datetime.timezone.utc)),
        ),
    ]
