# Generated by Django 4.2 on 2023-04-10 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_alter_students_last_time_at_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 3, 7, 31, 987509, tzinfo=datetime.timezone.utc)),
        ),
    ]
