# Generated by Django 4.2 on 2023-04-10 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('students_app', '0008_alter_students_last_time_at_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 4, 52, 19, 414252, tzinfo=datetime.timezone.utc)),
        ),
    ]
