# Generated by Django 4.2 on 2023-04-10 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_students_school_alter_students_last_time_at_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Student',
            fields=[
                ('students_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students_app.students')),
            ],
            bases=('students_app.students',),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 5, 6, 49, 824915, tzinfo=datetime.timezone.utc)),
        ),
    ]
