# Generated by Django 4.2 on 2023-04-10 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('students_app', '0011_alter_students_last_time_at_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_student',
            name='other_schools',
            field=models.ManyToManyField(to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 5, 40, 28, 371202, tzinfo=datetime.timezone.utc)),
        ),
    ]
