# Generated by Django 4.2 on 2023-04-10 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('students_app', '0012_exchange_student_other_schools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_student',
            name='other_schools',
            field=models.ManyToManyField(related_name='exchange_students', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_time_at_school',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 6, 1, 54, 791947, tzinfo=datetime.timezone.utc)),
        ),
    ]
